[features]
seeds = false
skip-lint = false
[programs.testnet]
# blob_chunks = "5dEVwohfk3ciDudFS7mXi35ET2e5nrQMnuWbis1J5PJ7"
copy = "BgaRwBpqNYbK8WSR4x1rtZn7LMhuwpHqF3nCoFtSjZjg"
# solana_da_programs = "FYTJ57g8BhUwVK5Y3d2KbBeHHe1hLrA5NckBbENssK3U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
